[build-system]
requires = ["setuptools >= 61.0", "wheel", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "xcdo"
dynamic = ["version"]
description = ""
authors = [{ name = "Prajeesh Ag", email = "prajeeshag@gmail.com" }]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cartopy>=0.24.1",
    "cftime>=1.6.4.post1",
    "clios>=0.2.1",
    "matplotlib>=3.9.2",
    "nc-time-axis>=1.4.1",
    "netcdf4>=1.7.2",
    "seaborn>=0.13.2",
    "typer>=0.13.1",
    "xarray>=2024.11,<2024.12",
    "zarr>=2.18.3",
]

[project.scripts]
# xcdo = "xcdo:app"

[project.urls]
homepage = "https://prajeeshag.github.io/xcdo"
repository = "https://github.com/prajeeshag/xcdo"
documentation = "https://prajeeshag.github.io/xcdo"

[tool.setuptools.packages.find]
where = ["."]
include = ["xcdo"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.setuptools_scm]
version_scheme = "guess-next-dev"
local_scheme = "node-and-timestamp"

[tool.setuptools.package-data]
"xcdo" = ["static/*"]

[tool.commitizen]
name = "cz_gitmoji"

[tool.uv]

[dependency-groups]
dev = ["ruff"]
test = ["pytest","pytest_mock", "pytest-sugar", "pytest-cov"]
docs = [
    "mkdocs",
    "mkdocs-material",
]
